# Generated by Django 3.1.1 on 2020-09-28 14:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Meme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auth_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProfileMeme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('meme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memeapp.meme')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memeapp.profile')),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='memes',
            field=models.ManyToManyField(through='memeapp.ProfileMeme', to='memeapp.Meme'),
        ),
    ]
