# Generated by Django 3.1.1 on 2020-10-27 14:27

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memeapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meme',
            name='embedding',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None),
        ),
        migrations.AddField(
            model_name='meme',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='meme',
            name='published_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='meme',
            name='shown_user_based',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='meme',
            name='watched',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='embedding',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None),
        ),
        migrations.AddField(
            model_name='profilememe',
            name='interacted_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='profilememe',
            name='score',
            field=models.IntegerField(choices=[(1, 'Like'), (-1, 'Dislike')]),
        ),
    ]
