# Generated by Django 3.1.1 on 2020-11-05 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memeapp', '0002_auto_20201027_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='tg_login',
            field=models.CharField(default='', max_length=100),
        ),
    ]
