# Generated by Django 3.1.1 on 2020-11-26 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memeapp', '0004_auto_20201119_2049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='auth_user',
        ),
    ]
