# Generated by Django 3.0.10 on 2020-11-26 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memeapp', '0005_remove_profile_auth_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='tg_login',
        ),
        migrations.AddField(
            model_name='profile',
            name='telegram_id',
            field=models.PositiveIntegerField(default=0, unique=True),
        ),
    ]
