# Generated by Django 3.0.10 on 2020-11-26 21:42

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memeapp', '0007_auto_20201126_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meme',
            name='embedding',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), default=list, size=None),
        ),
    ]
