# Generated by Django 3.0.10 on 2020-12-07 21:41

import django.contrib.postgres.fields
from django.db import migrations, models
import memeapp.recommend_engine.embedding_generator


class Migration(migrations.Migration):

    dependencies = [
        ('memeapp', '0008_auto_20201126_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meme',
            name='embedding',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), default=memeapp.recommend_engine.embedding_generator.default_meme_embedding, size=None),
        ),
        migrations.AlterField(
            model_name='profile',
            name='embedding',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), default=memeapp.recommend_engine.embedding_generator.default_user_embedding, size=None),
        ),
    ]
