# Generated by Django 3.1.4 on 2020-12-11 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memeapp', '0009_auto_20201207_2141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meme',
            name='shown_user_based',
        ),
        migrations.AddField(
            model_name='meme',
            name='is_new_criteria',
            field=models.BooleanField(default=True),
        ),
    ]
