# Generated by Django 3.1.4 on 2020-12-16 14:36

from django.db import migrations, models
import memeapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('memeapp', '0010_auto_20201211_2301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meme',
            name='image',
            field=models.ImageField(default=None, upload_to=memeapp.models.path_and_rename),
        ),
    ]
