# Generated by Django 3.1.4 on 2020-12-21 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memeapp', '0011_auto_20201216_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meme',
            name='checked',
            field=models.IntegerField(choices=[(1, 'Approved'), (0, 'On review'), (-1, 'Rejected')], default=0),
        ),
    ]
