# Generated by Django 3.1.4 on 2020-12-22 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('memeapp', '0012_auto_20201221_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='meme',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='memeapp.profile'),
        ),
        migrations.AddField(
            model_name='meme',
            name='hash',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
