# Generated by Django 3.1.4 on 2020-12-24 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memeapp', '0014_auto_20201222_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='meme',
            name='start',
            field=models.IntegerField(default=-1),
        ),
    ]
