# Generated by Django 3.1.4 on 2020-12-24 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memeapp', '0015_meme_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='start',
            field=models.IntegerField(default=-1),
        ),
    ]
