# Generated by Django 3.1.4 on 2021-01-04 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memeapp', '0016_profile_start'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meme',
            name='author',
        ),
        migrations.AddField(
            model_name='meme',
            name='origin',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='profilememe',
            name='score',
            field=models.IntegerField(choices=[(1, 'Like'), (0, 'Dislike')]),
        ),
    ]
