# Generated by Django 3.1.4 on 2021-01-11 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memeapp', '0018_profile_rejected'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='meme',
            index=models.Index(fields=['origin'], name='memeapp_mem_origin_f2f240_idx'),
        ),
        migrations.AddIndex(
            model_name='meme',
            index=models.Index(fields=['checked'], name='memeapp_mem_checked_d1fa27_idx'),
        ),
        migrations.AddIndex(
            model_name='meme',
            index=models.Index(fields=['published_on'], name='memeapp_mem_publish_8b5202_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['telegram_id'], name='memeapp_pro_telegra_055217_idx'),
        ),
        migrations.AddIndex(
            model_name='profilememe',
            index=models.Index(fields=['user'], name='memeapp_pro_user_id_537f7c_idx'),
        ),
        migrations.AddIndex(
            model_name='profilememe',
            index=models.Index(fields=['meme'], name='memeapp_pro_meme_id_815b59_idx'),
        ),
        migrations.AddIndex(
            model_name='profilememe',
            index=models.Index(fields=['interacted_on'], name='memeapp_pro_interac_7f5e77_idx'),
        ),
    ]
