# Generated by Django 3.1.4 on 2021-01-14 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memeapp', '0019_auto_20210111_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meme',
            name='published_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
