# Generated by Django 3.1.4 on 2021-01-14 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memeapp', '0020_auto_20210114_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='uploaded',
            field=models.BooleanField(default=False),
        ),
    ]
