# Generated by Django 3.1.4 on 2021-01-14 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memeapp', '0021_profile_uploaded'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='uploaded',
        ),
    ]
