# Generated by Django 3.1.4 on 2021-01-15 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memeapp', '0022_remove_profile_uploaded'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='nickname',
            field=models.CharField(default='', max_length=20),
        ),
    ]
