# Generated by Django 3.1.4 on 2021-01-16 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memeapp', '0023_profile_nickname'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='profile',
            name='memeapp_pro_telegra_055217_idx',
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['nickname'], name='memeapp_pro_nicknam_fe0a64_idx'),
        ),
    ]
