# Generated by Django 3.1.4 on 2021-01-18 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memeapp', '0026_auto_20210116_1909'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogReaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('meme_id', models.IntegerField()),
                ('score', models.IntegerField(choices=[(1, 'Like'), (0, 'Dislike')])),
                ('interacted_on', models.DateTimeField(auto_now_add=True)),
                ('recommend_detail', models.IntegerField()),
                ('responce_time', models.IntegerField()),
            ],
        ),
    ]
