# Generated by Django 3.1.4 on 2021-01-18 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memeapp', '0027_logreaction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logreaction',
            old_name='responce_time',
            new_name='response_time',
        ),
        migrations.RenameField(
            model_name='logreaction',
            old_name='interacted_on',
            new_name='timestamp',
        ),
    ]
