# Generated by Django 3.1.4 on 2021-01-19 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memeapp', '0028_auto_20210118_2023'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logreaction',
            old_name='recommend_detail',
            new_name='reacted_recommend_detail',
        ),
    ]
