# Generated by Django 3.0.13 on 2021-05-03 13:11

import django.contrib.postgres.fields
from django.db import migrations, models
import memeapp.preprocessing.text_embeddings
import memeapp.preprocessing.visual_embeddings


class Migration(migrations.Migration):

    dependencies = [
        ('memeapp', '0031_invite'),
    ]

    operations = [
        migrations.AddField(
            model_name='meme',
            name='lang',
            field=models.CharField(default='rus', max_length=5),
        ),
        migrations.AddField(
            model_name='meme',
            name='text',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='meme',
            name='text_embedding',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), default=memeapp.preprocessing.text_embeddings.default_text_embedding, size=None),
        ),
        migrations.AddField(
            model_name='meme',
            name='visual_embedding',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), default=memeapp.preprocessing.visual_embeddings.default_visual_embedding, size=None),
        ),
    ]
