# Generated by Django 3.1.4 on 2021-05-12 15:06

from django.db import migrations, models
import memeapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('memeapp', '0033_auto_20210506_1116'),
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default=None, upload_to=memeapp.models.path_and_rename_template)),
                ('published_on', models.DateTimeField(auto_now_add=True)),
                ('text', models.CharField(default='', max_length=5000)),
                ('telegram_id', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='meme',
            name='image',
            field=models.ImageField(default=None, upload_to=memeapp.models.path_and_rename_meme),
        ),
    ]
