# Generated by Django 3.1.4 on 2021-05-12 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memeapp', '0034_auto_20210512_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='telegram_id',
            field=models.CharField(max_length=200),
        ),
    ]
