# Generated by Django 3.1.7 on 2021-05-16 20:33

import django.contrib.postgres.fields
from django.db import migrations, models
import memeapp.recommend_engine.embedding_generator


class Migration(migrations.Migration):

    dependencies = [
        ('memeapp', '0036_loginline'),
    ]

    operations = [
        migrations.AddField(
            model_name='meme',
            name='text_pca',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), default=memeapp.recommend_engine.embedding_generator.default_text_pca, size=None),
        ),
        migrations.AddField(
            model_name='meme',
            name='visual_pca',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), default=memeapp.recommend_engine.embedding_generator.default_visual_pca, size=None),
        ),
    ]
